name: GitHub Actions
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
env:
  # Name of the image in the ECR
  APP_IMAGE: php-kbc-project-restore

  # DockerHub login
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # AWS Credentials
  TEST_AWS_ACCESS_KEY_ID: "AKIAQ4QRYXTAGOBOAKWF"
  TEST_AWS_SECRET_ACCESS_KEY: "${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}"
  TEST_AWS_REGION: "eu-central-1"
  TEST_AWS_S3_BUCKET: "gh-actions-php-kbc-project-restore-s3filesbucket-5g7gktywpq6v"

  # Azure Credentials
  TEST_AZURE_ACCOUNT_NAME: "projectmigration"
  TEST_AZURE_ACCOUNT_KEY: ${{ secrets.TEST_AZURE_ACCOUNT_KEY }}
  TEST_AZURE_CONTAINER_NAME: "test-restore-project"

  # KBC Credentials
  TEST_STORAGE_API_URL: "https://connection.keboola.com/"
  TEST_STORAGE_API_TOKEN: "${{ secrets.TEST_STORAGE_API_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app_image_tag: ${{ steps.tag.outputs.app_image_tag }}
      is_semantic_tag: ${{ steps.tag.outputs.is_semantic_tag }}
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Print Docker version
        run: docker -v
      -
        name: Docker login
        if: env.DOCKERHUB_TOKEN
        run: docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
      -
        name: Build image
        run: docker build -t $APP_IMAGE .
      -
        name: Run tests
        run: docker run
          -e TEST_STORAGE_API_URL
          -e TEST_STORAGE_API_TOKEN
          -e TEST_AWS_ACCESS_KEY_ID
          -e TEST_AWS_SECRET_ACCESS_KEY
          -e TEST_AWS_REGION
          -e TEST_AWS_S3_BUCKET
          -e TEST_AZURE_ACCOUNT_NAME
          -e TEST_AZURE_ACCOUNT_KEY
          -e TEST_AZURE_CONTAINER_NAME
          ${{env.APP_IMAGE}}
          composer ci
